force-app/main/default/objects/cicloLectivo__c/cicloLectivo__c.object-meta.xml
<CustomObject>
    <label>Ciclo Lectivo</label>
    <nameField>
        <label>Nombre de Ciclo Lectivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos Lectivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/anoEscolar__c.field-meta.xml
<CustomField>
    <fullName>anoEscolar__c</fullName>
    <label>Año escolar</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/cicloLectivo__c.field-meta.xml
<CustomField>
    <fullName>cicloLectivo__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ciclo Lectivo</label>
    <referenceTo>cicloLectivo__c</referenceTo>
    <relationshipLabel>Divisiones</relationshipLabel>
    <relationshipName>Divisiones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/nombre__c.field-meta.xml
<CustomField>
    <fullName>nombre__c</fullName>
    <formula>Text(anoEscolar__c) + &apos; &apos; + subdivision__c  +  &apos; &apos; + Text(Year(cicloLectivo__r.inicio__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>nombre</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/subdivision__c.field-meta.xml
<CustomField>
    <fullName>subdivision__c</fullName>
    <label>subdivision</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDivisionTrigger.cls
@isTest
public class TestDivisionTrigger {
    static private Map<String,Division__c> divisiones;

    @IsTest
    static void testRecordNames(){
        
        Test.startTest();
        // Valida el insert 
        TestDivisionTrigger.getDivisiones();
        Division__c division = [Select Name, nombre__c From Division__c Limit 1];
        System.assertEquals(division.Name, division.nombre__c);
        // Valida el update
        division.anoEscolar__c = 2;
        division.subdivision__c = 'C';
        update division;
        Division__c divisionActualizada = [Select Name, nombre__c From Division__c Limit 1];
        System.assertEquals(divisionActualizada.Name, divisionActualizada.nombre__c);


        Test.stopTest();
        
    }

    static public Map<String, Division__c> getDivisiones(){
        if ( divisiones == null ) {
            CicloLectivo__c ciclo = TestCicloTrigger.getCiclos().get(0);    
            divisiones = new Map<String, Division__c>();
            divisiones.put( '1A', new Division__c( CicloLectivo__c = ciclo.Id, anoEscolar__c = 1, subdivision__c = 'A' ) );
            divisiones.put( '1B', new Division__c( CicloLectivo__c = ciclo.Id, anoEscolar__c = 1, subdivision__c = 'B' ) );
            insert divisiones.values();
        }
        return divisiones;
    }
}