force-app/main/default/objects/cicloLectivo__c/cicloLectivo__c.object-meta.xml
<CustomObject>
    <label>Ciclo Lectivo</label>
    <nameField>
        <label>Nombre de Ciclo Lectivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos Lectivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cicloLectivo__c/fields/fin__c.field-meta.xml
<CustomField>
    <fullName>fin__c</fullName>
    <label>Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cicloLectivo__c/fields/inicio__c.field-meta.xml
<CustomField>
    <fullName>inicio__c</fullName>
    <label>Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestCicloTrigger.cls
public with sharing class TestCicloTrigger {
    static private List<CicloLectivo__c> ciclos; 

    static public List<CicloLectivo__c> getCiclos(){
        if ( ciclos == null) {
            ciclos = new List<CicloLectivo__c>();
            ciclos.add( new CicloLectivo__c( Name = 'Test', Inicio__c = Date.Today().addDays(-1), Fin__c = Date.Today().addDays(120) ) );
            insert ciclos;
        }
        return ciclos;
    }
}