force-app/main/default/objects/cicloLectivo__c/cicloLectivo__c.object-meta.xml
<CustomObject>
    <label>Ciclo Lectivo</label>
    <nameField>
        <label>Nombre de Ciclo Lectivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos Lectivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cicloLectivo__c/fields/cicloAnterior__c.field-meta.xml
<CustomField>
    <fullName>cicloAnterior__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciclo Anterior</label>
    <referenceTo>cicloLectivo__c</referenceTo>
    <relationshipLabel>cicloLectivo</relationshipLabel>
    <relationshipName>cicloLectivo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cicloLectivo__c/fields/fin__c.field-meta.xml
<CustomField>
    <fullName>fin__c</fullName>
    <label>Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cicloLectivo__c/fields/inicio__c.field-meta.xml
<CustomField>
    <fullName>inicio__c</fullName>
    <label>Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/cicloLectivo__c.field-meta.xml
<CustomField>
    <fullName>cicloLectivo__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ciclo Lectivo</label>
    <referenceTo>cicloLectivo__c</referenceTo>
    <relationshipLabel>Divisiones</relationshipLabel>
    <relationshipName>Divisiones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grilla__c/Grilla__c.object-meta.xml
<CustomObject>
    <label>Grilla de Materias</label>
    <nameField>
        <displayFormat>GR-{0000}-{YY}</displayFormat>
        <label>Nombre de Grilla</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grilla de Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grilla__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipName>Grilla</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grilla__c/fields/Docente__c.field-meta.xml
<CustomField>
    <fullName>Docente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Docente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Docente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Grilla</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grilla__c/fields/Materia__c.field-meta.xml
<CustomField>
    <fullName>Materia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Materia</label>
    <referenceTo>Materia__c</referenceTo>
    <relationshipName>Grilla_de_horarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Materia__c/Materia__c.object-meta.xml
<CustomObject>
    <label>Materia</label>
    <nameField>
        <label>Nombre de Materia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DivisionHelper.cls
public with sharing class DivisionHelper {

    public static List<WeekHelper.Semana> getSemanas(Id divisionId) {
        Division__c division = [SELECT CicloLectivo__r.inicio__c, CicloLectivo__r.fin__c FROM Division__c WHERE ID = :divisionId];
        return WeekHelper.getWeeksRange(division.CicloLectivo__r.inicio__c, division.CicloLectivo__r.fin__c);
    }

    public static List<Grilla__c> getGrilla( Id divisionId){
        List<Grilla__c>  materias = [Select Id, Materia__c, Materia__r.Name, Docente__c, Docente__r.Name  FROM Grilla__c WHERE Division__c = :divisionId];
        return materias;
    }

}