force-app/main/default/objects/cicloLectivo__c/cicloLectivo__c.object-meta.xml
<CustomObject>
    <label>Ciclo Lectivo</label>
    <nameField>
        <label>Nombre de Ciclo Lectivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos Lectivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cicloLectivo__c/fields/cicloAnterior__c.field-meta.xml
<CustomField>
    <fullName>cicloAnterior__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciclo Anterior</label>
    <referenceTo>cicloLectivo__c</referenceTo>
    <relationshipLabel>cicloLectivo</relationshipLabel>
    <relationshipName>cicloLectivo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/anoEscolar__c.field-meta.xml
<CustomField>
    <fullName>anoEscolar__c</fullName>
    <label>Año escolar</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/Capacidad__c.field-meta.xml
<CustomField>
    <fullName>Capacidad__c</fullName>
    <description>Capacidad maxima de alumnos</description>
    <label>Capacidad</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/cicloLectivo__c.field-meta.xml
<CustomField>
    <fullName>cicloLectivo__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ciclo Lectivo</label>
    <referenceTo>cicloLectivo__c</referenceTo>
    <relationshipLabel>Divisiones</relationshipLabel>
    <relationshipName>Divisiones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/subdivision__c.field-meta.xml
<CustomField>
    <fullName>subdivision__c</fullName>
    <label>subdivision</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CicloLectivoTriggerHelper.cls
public with sharing class CicloLectivoTriggerHelper {

    static public Set<Id> getCiclosAnteriores(List<CicloLectivo__c> ciclos) {
        Set<Id> ciclosPrevios = new Set<Id>();
        for ( CicloLectivo__c ciclo: ciclos) {
            if ( !String.isBlank(ciclo.cicloAnterior__c) )  {
                ciclosPrevios.add(ciclo.cicloAnterior__c);
            }
        }
        return ciclosPrevios;
    }
    
    static public void verificarCicloAnterior(List<CicloLectivo__c> newCicloLectivos) {
        Set<Id> ciclosPrevios = getCiclosAnteriores(newCicloLectivos) ;

        List<CicloLectivo__c> cicloAnteriorDuplicado =  [SELECT Id, cicloAnterior__c FROM CicloLectivo__c WHERE cicloAnterior__c IN :ciclosPrevios];

        if ( cicloAnteriorDuplicado.size() > 0 ) {
            Set<Id> ciclosDuplicados = getCiclosAnteriores(cicloAnteriorDuplicado);

            for ( CicloLectivo__c ciclo :newCicloLectivos) {
                if( ciclosDuplicados.contains(ciclo.cicloAnterior__c ) ) {
                    ciclo.addError('El ciclo ' + ciclo.name + ' contiene un ciclo anterior que ya tiene su proximo ciclo ' );
                }
            }
        }
    }

    static public void importDivisiones(List<CicloLectivo__c> newCicloLectivos) {
        Map<Id,Id> mapCiclosPrevios = new Map<Id,Id>();
        for ( CicloLectivo__c ciclo: newCicloLectivos) {
            if ( !String.isBlank(ciclo.cicloAnterior__c) )  {
                mapCiclosPrevios.put(ciclo.cicloAnterior__c, ciclo.Id);
            }
        }
        if ( mapCiclosPrevios.size() > 0 ) {
            List<Division__c> divisiones = [Select Id, anoEscolar__c, subDivision__c, capacidad__c, CicloLectivo__c FROM Division__c WHERE CicloLectivo__c IN :mapCiclosPrevios.keySet()];
            List<Division__c> newDivisiones = new List<Division__c>();

            for( Division__c division: divisiones){
                Division__c newDivision = division.clone(false);                
                newDivision.CicloLectivo__c = mapCiclosPrevios.get(division.CicloLectivo__c);
                newDivisiones.add( newDivision);
            }
            insert newDivisiones;
        }
    }
}