force-app/main/default/objects/cicloLectivo__c/cicloLectivo__c.object-meta.xml
<CustomObject>
    <label>Ciclo Lectivo</label>
    <nameField>
        <label>Nombre de Ciclo Lectivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos Lectivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cicloLectivo__c/fields/cicloAnterior__c.field-meta.xml
<CustomField>
    <fullName>cicloAnterior__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciclo Anterior</label>
    <referenceTo>cicloLectivo__c</referenceTo>
    <relationshipLabel>cicloLectivo</relationshipLabel>
    <relationshipName>cicloLectivo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cicloLectivo__c/fields/fin__c.field-meta.xml
<CustomField>
    <fullName>fin__c</fullName>
    <label>Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cicloLectivo__c/fields/inicio__c.field-meta.xml
<CustomField>
    <fullName>inicio__c</fullName>
    <label>Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/cicloLectivo__c.field-meta.xml
<CustomField>
    <fullName>cicloLectivo__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ciclo Lectivo</label>
    <referenceTo>cicloLectivo__c</referenceTo>
    <relationshipLabel>Divisiones</relationshipLabel>
    <relationshipName>Divisiones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/test/TestCicloTrigger.cls
@IsTest
public with sharing class TestCicloTrigger {
    static private Map<String, CicloLectivo__c> ciclos; 

    @IsTest
    static void testProximoCiclo(){
        Test.startTest();

        CicloLectivo__c cicloAnterior = TestCicloTrigger.getCiclos().get('ciclo1');

        insert new CicloLectivo__c( Name = 'ciclo2', cicloAnterior__c = cicloAnterior.Id, Inicio__c = Date.Today().addDays(-1), Fin__c = Date.Today().addDays(120) );

        try {
            insert new CicloLectivo__c( Name = 'ciclo3', cicloAnterior__c = cicloAnterior.Id, Inicio__c = Date.Today().addDays(-1), Fin__c = Date.Today().addDays(120) );
        } catch (DmlException ex) {
            System.assert(ex.getMessage().contains('contiene un ciclo anterior que ya tiene su proximo ciclo'));
        }
        Test.stopTest();

    }

    @IsTest
    static void testImportarDivisiones(){
        Test.startTest();

        CicloLectivo__c cicloAnterior = TestCicloTrigger.getCiclos().get('ciclo1');
        Integer totalDivisiones = TestDivisionTrigger.getDivisiones().size();
        
        CicloLectivo__c newCiclo = new CicloLectivo__c( Name = 'proximo ciclo', cicloAnterior__c = cicloAnterior.Id, Inicio__c = Date.Today().addDays(-1), Fin__c = Date.Today().addDays(120) );
        insert newCiclo;
    
        List<Division__c> divisiones =  [SELECT Id FROM Division__c Where CicloLectivo__c = :newCiclo.Id];
        System.assertEquals(totalDivisiones, divisiones.size());
        Test.stopTest();
    }


    static public Map<String, CicloLectivo__c> getCiclos(){
        if ( ciclos == null) {
            ciclos = new Map<String, CicloLectivo__c>();
            ciclos.put( 'ciclo1', new CicloLectivo__c( Name = 'ciclo1', Inicio__c = Date.Today().addDays(-1), Fin__c = Date.Today().addDays(120) ) );
            insert ciclos.values();
        }
        return ciclos;
    }
}