force-app/main/default/objects/Boletin__c/Boletin__c.object-meta.xml
<CustomObject>
    <label>Boletin</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boletines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boletin__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Boletines</relationshipLabel>
    <relationshipName>Boletines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestAsistenciasController.cls
@IsTest
public class TestAsistenciasController {

    @IsTest
    static void testGetAsistencias(){
        
        Test.startTest();
        Division__c division = TestDivisionTrigger.getDivisiones().get('1A');
        TestAsistenciasTrigger.getAsistencias();
        
        List<Boletin__c> asistencias =  AsistenciasController.getAsistencias(division.Id, 1);
        System.assertEquals(asistencias.size(),1);
        Test.stopTest();
        
    }

}