force-app/main/default/objects/Boletin__c/Boletin__c.object-meta.xml
<CustomObject>
    <label>Boletin</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boletines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evaluacion__c/Evaluacion__c.object-meta.xml
<CustomObject>
    <label>Evaluacion</label>
    <nameField>
        <displayFormat>EV# {00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Evaluacion__c/fields/Boletin__c.field-meta.xml
<CustomField>
    <fullName>Boletin__c</fullName>
    <label>Boletin</label>
    <referenceTo>Boletin__c</referenceTo>
    <relationshipLabel>Evaluaciones</relationshipLabel>
    <relationshipName>Evaluaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Grilla__c.field-meta.xml
<CustomField>
    <fullName>Grilla__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grilla de Materias</label>
    <referenceTo>Grilla__c</referenceTo>
    <relationshipLabel>Evaluaciones</relationshipLabel>
    <relationshipName>Evaluaciones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Nota1__c.field-meta.xml
<CustomField>
    <fullName>Nota1__c</fullName>
    <label>Nota1</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grilla__c/Grilla__c.object-meta.xml
<CustomObject>
    <label>Grilla de Materias</label>
    <nameField>
        <displayFormat>GR-{0000}-{YY}</displayFormat>
        <label>Nombre de Grilla</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grilla de Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/test/TestEvaluacionesTrigger.cls
@isTest
public class TestEvaluacionesTrigger {
    static private Map<String, Evaluacion__c> evaluaciones;

        public static Map<String, Evaluacion__c> getEvaluaciones(){
            return getEvaluaciones(true);
        }

        public static Map<String, Evaluacion__c> getEvaluaciones( Boolean insertValues){
        if ( evaluaciones == null ) {
            Boletin__c boletin = TestBoletinTrigger.getBoletines().get('Juan 1A');
            Grilla__c grilla = TestGrillaTrigger.getGrilla().get('lengua');

            evaluaciones = new Map<String, Evaluacion__c>();            
            evaluaciones.put( 'Juan 1A Lengua', new Evaluacion__c( Boletin__c =boletin.Id, Grilla__c = grilla.id, Nota1__c = 10) );
            if( insertValues ) {
                insert evaluaciones.values();
                system.debug(evaluaciones.values().size());
            } 
        }
        return evaluaciones;
    }
}