force-app/main/default/objects/Boletin__c/Boletin__c.object-meta.xml
<CustomObject>
    <label>Boletin</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boletines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boletin__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Boletines</relationshipLabel>
    <relationshipName>Boletines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cicloLectivo__c/cicloLectivo__c.object-meta.xml
<CustomObject>
    <label>Ciclo Lectivo</label>
    <nameField>
        <label>Nombre de Ciclo Lectivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos Lectivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/cicloLectivo__c.field-meta.xml
<CustomField>
    <fullName>cicloLectivo__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ciclo Lectivo</label>
    <referenceTo>cicloLectivo__c</referenceTo>
    <relationshipLabel>Divisiones</relationshipLabel>
    <relationshipName>Divisiones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/test/TestAsistenciasController.cls
@IsTest
public class TestAsistenciasController {

    @IsTest
    static void testGetAsistencias(){
        
        Test.startTest();
        Division__c division = TestDataFactory.getDivisiones().get('D-1');
        TestDataFactory.getAsistencias();

        // getSemanas de una division        
        AsistenciasController.getSemanas(division.Id);
        
        // asistencias de la division
        AsistenciasHelper.AsistenciasDivision result1 =  AsistenciasController.getByDivision(division.Id, 1);
        System.assertEquals(1, result1.asistencias.size());

        // asistencias del ciclo
        AsistenciasHelper.AsistenciasCiclo result2 =  AsistenciasController.getByCiclo(division.CicloLectivo__c);
        System.assertEquals(2, result2.asistencias.size());

        // asistencias del boletin
        Boletin__c boletin = TestDataFactory.getBoletines().get('B-1');        
        AsistenciasHelper.AsistenciasBoletin result3 =  AsistenciasController.getByBoletin(boletin.Id);
        System.assertEquals(2, result3.asistencias.size());

        Test.stopTest();   
    }

    @IsTest
    static void testSaveByBoletin(){
        
        List<Map<String, Object>>  draftValues = new List<Map<String, Object>>();
        draftValues.add( new Map<String,Object>{ 'Martes__c' => 'Asistio', 'Semana__c' => 1 } );

        Test.startTest();
        Boletin__c boletin = TestDataFactory.getBoletines().get('B-1');        

        AsistenciasController.saveByBoletin(boletin.Id, draftValues);

        Test.stopTest();   
    }
 
    @IsTest
    static void testSaveByDivision(){        
        Boletin__c boletin = TestDataFactory.getBoletines().get('B-1');        
        List<Map<String, Object>>  draftValues = new List<Map<String, Object>>();
        draftValues.add( new Map<String,Object>{ 'Martes__c' => 'Asistio', 'id' => boletin.Id } );
        
        Test.startTest();
        Division__c division = TestDataFactory.getDivisiones().get('D-1');
        
        AsistenciasController.saveByDivision(division.Id, 1, draftValues);
    
        Test.stopTest();   
    }
 
}