force-app/main/default/objects/Boletin__c/Boletin__c.object-meta.xml
<CustomObject>
    <label>Boletin</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boletines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boletin__c/fields/Alumno__c.field-meta.xml
<CustomField>
    <fullName>Alumno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Alumno</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Boletines</relationshipLabel>
    <relationshipName>Boletines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Boletines</relationshipLabel>
    <relationshipName>Boletines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/nombre__c.field-meta.xml
<CustomField>
    <fullName>nombre__c</fullName>
    <formula>Text(anoEscolar__c) + &apos; &apos; + subdivision__c  +  &apos; &apos; + Text(Year(cicloLectivo__r.inicio__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>nombre</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestBoletinTrigger.cls
@IsTest
public class TestBoletinTrigger {
    static private Map<String, Boletin__c> boletines;

    @IsTest
    static void testRecordNames(){
        

        Test.startTest();
        TestBoletinTrigger.getBoletines();
        Division__c division = [Select Name, nombre__c From Division__c Limit 1];
        System.assertEquals(division.Name, division.nombre__c);
        Test.stopTest();
        
    }
    public static Map<String, Boletin__c> getBoletines(){
        if ( boletines == null ) {
            Division__c division = TestDivisionTrigger.getDivisiones().get('1A');
            Contact alumno = TestContactTrigger.getAlumnos().get('Juan');
            boletines = new Map<String, Boletin__c>();
            boletines.put( 'Juan 1A', new Boletin__c( Division__c = division.Id, Alumno__c = alumno.Id) );
            insert boletines.values();
        }
        return boletines;
    }
}