force-app/main/default/objects/Boletin__c/Boletin__c.object-meta.xml
<CustomObject>
    <label>Boletin</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boletines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boletin__c/fields/Alumno__c.field-meta.xml
<CustomField>
    <fullName>Alumno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Alumno</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Boletines</relationshipLabel>
    <relationshipName>Boletines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Boletines</relationshipLabel>
    <relationshipName>Boletines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/nombreAlumno__c.field-meta.xml
<CustomField>
    <fullName>nombreAlumno__c</fullName>
    <formula>Alumno__r.FirstName + &apos; &apos; + Alumno__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre Completo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cicloLectivo__c/cicloLectivo__c.object-meta.xml
<CustomObject>
    <label>Ciclo Lectivo</label>
    <nameField>
        <label>Nombre de Ciclo Lectivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos Lectivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cicloLectivo__c/fields/cicloAnterior__c.field-meta.xml
<CustomField>
    <fullName>cicloAnterior__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciclo Anterior</label>
    <referenceTo>cicloLectivo__c</referenceTo>
    <relationshipLabel>cicloLectivo</relationshipLabel>
    <relationshipName>cicloLectivo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cicloLectivo__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programa</label>
    <referenceTo>Programa__c</referenceTo>
    <relationshipLabel>Ciclo Lectivos</relationshipLabel>
    <relationshipName>cicloLectivo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/cicloLectivo__c.field-meta.xml
<CustomField>
    <fullName>cicloLectivo__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ciclo Lectivo</label>
    <referenceTo>cicloLectivo__c</referenceTo>
    <relationshipLabel>Divisiones</relationshipLabel>
    <relationshipName>Divisiones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <formula>cicloLectivo__r.Programa__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Programa</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/Evaluacion__c.object-meta.xml
<CustomObject>
    <label>Evaluacion</label>
    <nameField>
        <displayFormat>EV# {00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Evaluacion__c/fields/Alumno__c.field-meta.xml
<CustomField>
    <fullName>Alumno__c</fullName>
    <formula>Boletin__r.Alumno__r.Nombre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alumno</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Boletin__c.field-meta.xml
<CustomField>
    <fullName>Boletin__c</fullName>
    <label>Boletin</label>
    <referenceTo>Boletin__c</referenceTo>
    <relationshipLabel>Evaluaciones</relationshipLabel>
    <relationshipName>Evaluaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Conceptual1__c.field-meta.xml
<CustomField>
    <fullName>Conceptual1__c</fullName>
    <label>Conceptual1</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Conceptual2__c.field-meta.xml
<CustomField>
    <fullName>Conceptual2__c</fullName>
    <label>Conceptual2</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Conceptual3__c.field-meta.xml
<CustomField>
    <fullName>Conceptual3__c</fullName>
    <label>Conceptual3</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Conceptual4__c.field-meta.xml
<CustomField>
    <fullName>Conceptual4__c</fullName>
    <label>Conceptual4</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Conceptual5__c.field-meta.xml
<CustomField>
    <fullName>Conceptual5__c</fullName>
    <label>Conceptual5</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Grilla__c.field-meta.xml
<CustomField>
    <fullName>Grilla__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grilla de Materias</label>
    <referenceTo>Grilla__c</referenceTo>
    <relationshipLabel>Evaluaciones</relationshipLabel>
    <relationshipName>Evaluaciones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Materia__c.field-meta.xml
<CustomField>
    <fullName>Materia__c</fullName>
    <formula>Grilla__r.Materia__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Materia</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Nota1__c.field-meta.xml
<CustomField>
    <fullName>Nota1__c</fullName>
    <label>Nota1</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Nota2__c.field-meta.xml
<CustomField>
    <fullName>Nota2__c</fullName>
    <label>Nota2</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Nota3__c.field-meta.xml
<CustomField>
    <fullName>Nota3__c</fullName>
    <label>Nota3</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Nota4__c.field-meta.xml
<CustomField>
    <fullName>Nota4__c</fullName>
    <label>Nota4</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Nota5__c.field-meta.xml
<CustomField>
    <fullName>Nota5__c</fullName>
    <label>Nota5</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Grilla__c/Grilla__c.object-meta.xml
<CustomObject>
    <label>Grilla de Materias</label>
    <nameField>
        <displayFormat>GR-{0000}-{YY}</displayFormat>
        <label>Nombre de Grilla</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grilla de Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grilla__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipName>Grilla</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grilla__c/fields/Materia__c.field-meta.xml
<CustomField>
    <fullName>Materia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Materia</label>
    <referenceTo>Materia__c</referenceTo>
    <relationshipName>Grilla_de_horarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Materia__c/Materia__c.object-meta.xml
<CustomObject>
    <label>Materia</label>
    <nameField>
        <label>Nombre de Materia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Materia__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programa</label>
    <referenceTo>Programa__c</referenceTo>
    <relationshipLabel>Materias</relationshipLabel>
    <relationshipName>Materias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Programa__c/Programa__c.object-meta.xml
<CustomObject>
    <label>Programa</label>
    <nameField>
        <label>Programa Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Programa__c/fields/Evaluaciones__c.field-meta.xml
<CustomField>
    <fullName>Evaluaciones__c</fullName>
    <label>Evaluaciones</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProgramaEvaluacion__c/ProgramaEvaluacion__c.object-meta.xml
<CustomObject>
    <description>Cada programa define los tipos de evalucaciones que quedaran reflejados como columnas del boletin. 
Cada materia pondra sus notas, ya sean conceptuales o numericas de acuerdo a esta definicion</description>
    <label>Evaluacion de un Programa</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluaciones de los programas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramaEvaluacion__c/fields/Campo__c.field-meta.xml
<CustomField>
    <fullName>Campo__c</fullName>
    <label>Campo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nota1__c</fullName>
                <label>Nota1</label>
            </value>
            <value>
                <fullName>Nota2__c</fullName>
                <label>Nota2</label>
            </value>
            <value>
                <fullName>Nota3__c</fullName>
                <label>Nota3</label>
            </value>
            <value>
                <fullName>Nota4__c</fullName>
                <label>Nota4</label>
            </value>
            <value>
                <fullName>Nota5__c</fullName>
                <label>Nota5</label>
            </value>
            <value>
                <fullName>Conceptual1__c</fullName>
                <label>Conceptual1</label>
            </value>
            <value>
                <fullName>Conceptual2__c</fullName>
                <label>Conceptual2</label>
            </value>
            <value>
                <fullName>Conceptual3__c</fullName>
                <label>Conceptual3</label>
            </value>
            <value>
                <fullName>Conceptual4__c</fullName>
                <label>Conceptual4</label>
            </value>
            <value>
                <fullName>Conceptual5__c</fullName>
                <label>Conceptual5</label>
            </value>
            <value>
                <fullName>Opcion1</fullName>
            </value>
            <value>
                <fullName>Opcion2</fullName>
            </value>
            <value>
                <fullName>Opcion3</fullName>
            </value>
            <value>
                <fullName>Opcion4</fullName>
            </value>
            <value>
                <fullName>Opcion5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramaEvaluacion__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <label>Programa</label>
    <referenceTo>Programa__c</referenceTo>
    <relationshipLabel>Evaluaciones de los programas</relationshipLabel>
    <relationshipName>ProgramaEvaluaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EvaluacionesHelper.cls
public with sharing class EvaluacionesHelper {
    public class ProgramaEvaluacion {
        @AuraEnabled public String tipo;
        @AuraEnabled public String nombre;
        @AuraEnabled public String campo;
        @AuraEnabled public List<String> opciones;
    }

    public class Programa {
        @AuraEnabled public List<ProgramaEvaluacion> evaluaciones;
    }
    
    static private Set<String> getFieldsEvaluaciones() {
        Set<String> fields = new Set<String>();
		Schema.DescribeFieldResult fieldResult = ProgramaEvaluacion__c.Campo__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			fields.add(pickListVal.getValue());
		}     
		return fields;        
    }

    public static Programa  getPrograma( Id divisionId){
        Programa programa;
        Division__c division = [Select CicloLectivo__r.Programa__r.Evaluaciones__c FROM Division__c WHERE Id = :divisionId];
        if ( !String.isBlank(division.CicloLectivo__r.Programa__r.Evaluaciones__c) ) {
            programa = (Programa)JSON.deserializeStrict(division.CicloLectivo__r.Programa__r.Evaluaciones__c, Programa.class);
        }
        return programa;
    }
    
    public class EvaluacionesGrilla {
        Id grillaId;
        @AuraEnabled public Programa programa;
        @AuraEnabled public List<Evaluacion__c> evaluaciones;

        public EvaluacionesGrilla( Id grillaId){
            this.grillaId = grillaId;
            retrieve();
        }
        void retrieve() {
            Grilla__c grilla = [Select Division__r.CicloLectivo__r.Programa__r.Evaluaciones__c FROM Grilla__c WHERE Id = :this.grillaId];
            if ( !String.isBlank(grilla.Division__r.CicloLectivo__r.Programa__r.Evaluaciones__c) ) {
                programa = (Programa)JSON.deserializeStrict(grilla.Division__r.CicloLectivo__r.Programa__r.Evaluaciones__c, Programa.class);
            }
            evaluaciones = [SELECT Id, Alumno__c, Materia__c, Conceptual1__c, Conceptual2__c, Conceptual3__c, Conceptual4__c, Conceptual5__c,  Nota1__c, Nota2__c, Nota3__c, Nota4__c, Nota5__c 
                    FROM Evaluacion__c 
                    WHERE Grilla__c = :this.grillaId];

        }
    }

    public class EvaluacionesBoletin {
        Id boletinId;
        @AuraEnabled public Programa programa;
        @AuraEnabled public List<Evaluacion__c> evaluaciones;

        public EvaluacionesBoletin( Id boletinId){
            this.boletinId = boletinId;
            retrieve();
        }

        public void save(List<Map<String, Object>> draftValues) {
            
        }

        void retrieve() {
            Boletin__c boletin = [Select Division__r.CicloLectivo__r.Programa__r.Evaluaciones__c FROM Boletin__c WHERE Id = :this.boletinId];
            if ( !String.isBlank(boletin.Division__r.CicloLectivo__r.Programa__r.Evaluaciones__c) ) {
                programa = (Programa) JSON.deserializeStrict(boletin.Division__r.CicloLectivo__r.Programa__r.Evaluaciones__c, Programa.class);
            }

            evaluaciones = [SELECT Id, Materia__c, Conceptual1__c, Conceptual2__c, Conceptual3__c, Conceptual4__c, Conceptual5__c , Nota1__c, Nota2__c, Nota3__c, Nota4__c, Nota5__c
                    FROM Evaluacion__c 
                    WHERE Boletin__c = :this.boletinId];
        }
    }

    public class EvaluacionesDivision {
        public Id divisionId;
        public Id grillaId;
        @AuraEnabled public List<Boletin__c> evaluaciones;

        public EvaluacionesDivision( Id divisionId, Id grillaId){
            this.divisionId = divisionId;
            this.grillaId = grillaId;
            retrieve();            
        }

        public void save(List<Map<String, Object>> draftValues) {
            try {
                Set<String> fieldsEvaluaciones= EvaluacionesHelper.getFieldsEvaluaciones();
                List<Evaluacion__c> evaluaciones = new List<Evaluacion__c>();
                for ( Map<String, Object> draft :draftValues ) {
                    Evaluacion__c evaluacion = new Evaluacion__c( Boletin__c = (String)draft.get('id'), Grilla__c = this.grillaId);
                    evaluacion.UniqueKey__c = evaluacion.Boletin__c + '-' + evaluacion.Grilla__c;
                    for ( String columnName : draft.keySet() ){
                        
                        if ( fieldsEvaluaciones.contains(columnName) ) {
                            evaluacion.put( columnName, draft.get(columnName));
                        }
                    }
                    evaluaciones.add(evaluacion);
                }    
                upsert evaluaciones UniqueKey__c;
            } catch ( Exception e ){
                System.debug(e.getMessage());
                throw new AuraHandledException('Se produjo un error al guardar' + e.getMessage());    
            }
        }            

        void retrieve() {
            evaluaciones = [SELECT Id, Alumno__c, nombreAlumno__c,
                ( SELECT Conceptual1__c, Conceptual2__c, Conceptual3__c, Conceptual4__c, Conceptual5__c , Nota1__c, Nota2__c, Nota3__c, Nota4__c, Nota5__c 
                FROM Evaluaciones__r 
                WHERE Grilla__c = :grillaId )
            FROM Boletin__c
            WHERE Division__c = :this.divisionId];
        }
    }

}