force-app/main/default/objects/Boletin__c/Boletin__c.object-meta.xml
<CustomObject>
    <label>Boletin</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boletines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boletin__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Boletines</relationshipLabel>
    <relationshipName>Boletines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <formula>cicloLectivo__r.Programa__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Programa</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grilla__c/Grilla__c.object-meta.xml
<CustomObject>
    <label>Grilla de Materias</label>
    <nameField>
        <displayFormat>GR-{0000}-{YY}</displayFormat>
        <label>Nombre de Grilla</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grilla de Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grilla__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipName>Grilla</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Programa__c/Programa__c.object-meta.xml
<CustomObject>
    <label>Programa</label>
    <nameField>
        <label>Programa Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/test/TestEvaluacionesController.cls
@IsTest
public class TestEvaluacionesController {

    @IsTest
    static void testGetEvaluaciones(){
        
        Test.startTest();
        Programa__c programa = TestProgramaTrigger.getProgramas().get('P1');
        Division__c division = TestDivisionTrigger.getDivisiones().get('1A');
        Grilla__c grilla = TestGrillaTrigger.getGrilla().get('lengua');
        TestEvaluacionesTrigger.getEvaluaciones();
        Boletin__c boletin = TestBoletinTrigger.getBoletines().get('Juan 1A');

        // asistencias del programa
        EvaluacionesController.getPrograma(programa.Id);

        // asistencias de la grilla
        EvaluacionesHelper.EvaluacionesGrilla result1 =  EvaluacionesController.getByGrilla(grilla.Id);
        System.assertEquals(1, result1.evaluaciones.size());
        
        // asistencias del la division
        EvaluacionesHelper.EvaluacionesDivision result2 =  EvaluacionesController.getByDivision(division.Id, grilla.Id);
        System.assertEquals(2, result2.evaluaciones.size());

        // asistencias del boletin
        EvaluacionesHelper.EvaluacionesBoletin result3 =  EvaluacionesController.getByBoletin(boletin.Id);
        System.assertEquals(1, result3.evaluaciones.size());

        Test.stopTest();   
    }

    @IsTest
    static void testSaveByBoletin(){
        Grilla__c grilla = TestGrillaTrigger.getGrilla().get('lengua');
        Boletin__c boletin = TestBoletinTrigger.getBoletines().get('Juan 1A');        
        
        List<Map<String, Object>>  draftValues = new List<Map<String, Object>>();
        draftValues.add( new Map<String,Object>{ 'Nota1__c' => 10, 'Grilla__c' => grilla.Id } );

        Test.startTest();

        EvaluacionesController.saveByBoletin(boletin.Id, draftValues);

        Test.stopTest();   
    }
 
    @IsTest
    static void testSaveByDivision(){        
        Division__c division = TestDivisionTrigger.getDivisiones().get('1A');
        Grilla__c grilla = TestGrillaTrigger.getGrilla().get('lengua');
        Boletin__c boletin = TestBoletinTrigger.getBoletines().get('Juan 1A');        
        List<Map<String, Object>>  draftValues = new List<Map<String, Object>>();
        draftValues.add( new Map<String,Object>{ 'Nota1__c' => 10, 'id' => boletin.Id } );
        
        Test.startTest();
        
        EvaluacionesController.saveByDivision(division.Id, grilla.Id, draftValues);
    
        Test.stopTest();   
    }

    
    //
    //EvaluacionesController.saveEvaluaciones(evaluaciones)
    
}