force-app/main/default/objects/Materia__c/Materia__c.object-meta.xml
<CustomObject>
    <label>Materia</label>
    <nameField>
        <label>Nombre de Materia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Materia__c/fields/anoEscolar__c.field-meta.xml
<CustomField>
    <fullName>anoEscolar__c</fullName>
    <description>El Año escolar representa el año dentro del programa. Se asume que un programa tiene como maximo 9 años</description>
    <inlineHelpText>Año dentro del programa, por ejemplo 1 seria primer año.</inlineHelpText>
    <label>Año escolar</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/test/TestMateriaTrigger.cls
@IsTest
public with sharing class TestMateriaTrigger {
    static private Map<String, Materia__c> materias;
    public static Map<String, Materia__c> getMaterias(){
        if ( materias == null ) {            
            materias = new Map<String, Materia__c>();
            materias.put( 'matematica', new Materia__c( Name = 'Matematica', anoEscolar__c=1) );
            materias.put( 'lengua', new Materia__c( Name = 'Lengua', anoEscolar__c=1) );
            materias.put( 'fisica', new Materia__c( Name = 'Fisica', anoEscolar__c=1) );
            insert materias.values();
        }
        return materias;
    }

}