force-app/main/default/objects/Programa__c/Programa__c.object-meta.xml
<CustomObject>
    <label>Programa</label>
    <nameField>
        <label>Programa Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Programa__c/fields/Evaluaciones__c.field-meta.xml
<CustomField>
    <fullName>Evaluaciones__c</fullName>
    <label>Evaluaciones</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/test/TestProgramaTrigger.cls
@isTest
public class TestProgramaTrigger {

    @isTest
    static void testEvaluaciones(){
        Test.startTest();
        TestDataFactory.getProgramaEvaluaciones();
        
        Programa__c programa = [SELECT Evaluaciones__c FROM Programa__c LIMIT 1];
        try  {
            EvaluacionesHelper.Programa evaluaciones = (EvaluacionesHelper.Programa)JSON.deserializeStrict(programa.Evaluaciones__c, EvaluacionesHelper.Programa.class);
        } catch( Exception error ){
            System.assert(true, 'Tiene que generar el json' );
        }

        Test.stopTest();
    }

}