force-app/main/default/objects/Programa__c/Programa__c.object-meta.xml
<CustomObject>
    <label>Programa</label>
    <nameField>
        <label>Programa Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramaEvaluacion__c/ProgramaEvaluacion__c.object-meta.xml
<CustomObject>
    <description>Cada programa define los tipos de evalucaciones que quedaran reflejados como columnas del boletin. 
Cada materia pondra sus notas, ya sean conceptuales o numericas de acuerdo a esta definicion</description>
    <label>Evaluacion de un Programa</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluaciones de los programas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramaEvaluacion__c/fields/Campo__c.field-meta.xml
<CustomField>
    <fullName>Campo__c</fullName>
    <label>Campo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nota1__c</fullName>
                <label>Nota1</label>
            </value>
            <value>
                <fullName>Nota2__c</fullName>
                <label>Nota2</label>
            </value>
            <value>
                <fullName>Nota3__c</fullName>
                <label>Nota3</label>
            </value>
            <value>
                <fullName>Nota4__c</fullName>
                <label>Nota4</label>
            </value>
            <value>
                <fullName>Nota5__c</fullName>
                <label>Nota5</label>
            </value>
            <value>
                <fullName>Conceptual1__c</fullName>
                <label>Conceptual1</label>
            </value>
            <value>
                <fullName>Conceptual2__c</fullName>
                <label>Conceptual2</label>
            </value>
            <value>
                <fullName>Conceptual3__c</fullName>
                <label>Conceptual3</label>
            </value>
            <value>
                <fullName>Conceptual4__c</fullName>
                <label>Conceptual4</label>
            </value>
            <value>
                <fullName>Conceptual5__c</fullName>
                <label>Conceptual5</label>
            </value>
            <value>
                <fullName>Opcion1</fullName>
            </value>
            <value>
                <fullName>Opcion2</fullName>
            </value>
            <value>
                <fullName>Opcion3</fullName>
            </value>
            <value>
                <fullName>Opcion4</fullName>
            </value>
            <value>
                <fullName>Opcion5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramaEvaluacion__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <label>Programa</label>
    <referenceTo>Programa__c</referenceTo>
    <relationshipLabel>Evaluaciones de los programas</relationshipLabel>
    <relationshipName>ProgramaEvaluaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProgramaEvaluacion__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Las notas son valoraciones numericas del 1 al 10, mientras que las conceptuales son listas de valoraciones por ejemplo Insuficiente, Regular. Bien, Muy Bien y Excelente.</description>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nota</fullName>
            </value>
            <value>
                <fullName>Conceptual</fullName>
            </value>
            <value>
                <fullName>Formula</fullName>
            </value>
            <value>
                <fullName>Opcion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/test/TestProgramaEvaluacionTrigger.cls
@IsTest
public class TestProgramaEvaluacionTrigger {

    static private Map<String, ProgramaEvaluacion__c> programaEvaluaciones;

        public static Map<String, ProgramaEvaluacion__c> getProgramaEvaluaciones(){
            return getProgramaEvaluaciones(true);
        }

        public static Map<String, ProgramaEvaluacion__c> getProgramaEvaluaciones( Boolean insertValues){
        if ( programaEvaluaciones == null ) {
            programaEvaluaciones = new Map<String, ProgramaEvaluacion__c>(); 
            Programa__c programa = TestProgramaTrigger.getProgramas().get('P1');

            programaEvaluaciones.put( 'P1', new ProgramaEvaluacion__c( Programa__c = programa.Id,  Tipo__c = 'Nota', Campo__c = 'Nota1__c'));
            programaEvaluaciones.put( 'P1', new ProgramaEvaluacion__c( Programa__c = programa.Id,  Tipo__c = 'Nota', Campo__c = 'Nota2__c'));

            if( insertValues ) {
                insert programaEvaluaciones.values();
            } 
        }
        return programaEvaluaciones;
    }    

}