force-app/main/default/objects/Programa__c/Programa__c.object-meta.xml
<CustomObject>
    <label>Programa</label>
    <nameField>
        <label>Programa Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Programa__c/fields/Evaluaciones__c.field-meta.xml
<CustomField>
    <fullName>Evaluaciones__c</fullName>
    <label>Evaluaciones</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProgramaEvaluacion__c/ProgramaEvaluacion__c.object-meta.xml
<CustomObject>
    <description>Cada programa define los tipos de evalucaciones que quedaran reflejados como columnas del boletin. 
Cada materia pondra sus notas, ya sean conceptuales o numericas de acuerdo a esta definicion</description>
    <label>Evaluacion de un Programa</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluaciones de los programas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramaEvaluacion__c/fields/Campo__c.field-meta.xml
<CustomField>
    <fullName>Campo__c</fullName>
    <label>Campo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nota1__c</fullName>
                <label>Nota1</label>
            </value>
            <value>
                <fullName>Nota2__c</fullName>
                <label>Nota2</label>
            </value>
            <value>
                <fullName>Nota3__c</fullName>
                <label>Nota3</label>
            </value>
            <value>
                <fullName>Nota4__c</fullName>
                <label>Nota4</label>
            </value>
            <value>
                <fullName>Nota5__c</fullName>
                <label>Nota5</label>
            </value>
            <value>
                <fullName>Conceptual1__c</fullName>
                <label>Conceptual1</label>
            </value>
            <value>
                <fullName>Conceptual2__c</fullName>
                <label>Conceptual2</label>
            </value>
            <value>
                <fullName>Conceptual3__c</fullName>
                <label>Conceptual3</label>
            </value>
            <value>
                <fullName>Conceptual4__c</fullName>
                <label>Conceptual4</label>
            </value>
            <value>
                <fullName>Conceptual5__c</fullName>
                <label>Conceptual5</label>
            </value>
            <value>
                <fullName>Opcion1</fullName>
            </value>
            <value>
                <fullName>Opcion2</fullName>
            </value>
            <value>
                <fullName>Opcion3</fullName>
            </value>
            <value>
                <fullName>Opcion4</fullName>
            </value>
            <value>
                <fullName>Opcion5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramaEvaluacion__c/fields/Opciones__c.field-meta.xml
<CustomField>
    <fullName>Opciones__c</fullName>
    <label>Opciones</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProgramaEvaluacion__c/fields/Orden__c.field-meta.xml
<CustomField>
    <fullName>Orden__c</fullName>
    <label>Orden</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProgramaEvaluacion__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <label>Programa</label>
    <referenceTo>Programa__c</referenceTo>
    <relationshipLabel>Evaluaciones de los programas</relationshipLabel>
    <relationshipName>ProgramaEvaluaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProgramaEvaluacion__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Las notas son valoraciones numericas del 1 al 10, mientras que las conceptuales son listas de valoraciones por ejemplo Insuficiente, Regular. Bien, Muy Bien y Excelente.</description>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nota</fullName>
            </value>
            <value>
                <fullName>Conceptual</fullName>
            </value>
            <value>
                <fullName>Formula</fullName>
            </value>
            <value>
                <fullName>Opcion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProgramaEvaluacionTriggerHelper.cls
public with sharing class ProgramaEvaluacionTriggerHelper {

    static public void updatePrograma(List<ProgramaEvaluacion__c> evaluaciones) {
        Set<Id> idProgramas = getProgramas(evaluaciones);
        List<Programa__c> programas = [Select Id, (SELECT Id, Name, Campo__c, Opciones__c , Tipo__c FROM ProgramaEvaluaciones__r ORDER BY Orden__c) 
            FROM Programa__c 
            WHERE Id IN :idProgramas];

        for( Programa__c programa :programas){
            programa.Evaluaciones__c = getEvaluacionesJSON(programa.ProgramaEvaluaciones__r).getAsString();
        }
        update programas;
    }

    static System.JSONGenerator getEvaluacionesJSON( List<ProgramaEvaluacion__c> evaluaciones){
        System.JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
            gen.writeFieldName('evaluaciones');
                gen.writeStartArray();
                    for ( ProgramaEvaluacion__c evaluacion :evaluaciones){
                        gen.writeStartObject();
                        gen.writeStringField('nombre', evaluacion.Name);
                        gen.writeStringField('campo', evaluacion.Campo__c);
                        gen.writeStringField('tipo', evaluacion.Tipo__c);
                        if ( evaluacion.Tipo__c == 'Conceptual') {
                            gen.writeFieldName('opciones');
                            gen.writeStartArray();
                            for ( String opcion: evaluacion.Opciones__c.split(',') ) {
                                gen.writeString(opcion);
                            }
                            gen.writeEndArray();
                        }
                        gen.writeEndObject();
                    }
                gen.writeEndArray();
        gen.writeEndObject();
        return gen;
    }

    static public Set<Id> getProgramas(List<ProgramaEvaluacion__c> evaluaciones) {        
        return TriggerHelper.getIdsFromSObjects(evaluaciones, 'Programa__c');
    }

    
}