force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grilla__c/Grilla__c.object-meta.xml
<CustomObject>
    <label>Grilla de Materias</label>
    <nameField>
        <displayFormat>GR-{0000}-{YY}</displayFormat>
        <label>Nombre de Grilla</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grilla de Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grilla__c/fields/Auxiliar__c.field-meta.xml
<CustomField>
    <fullName>Auxiliar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Auxiliar</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Docente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Grilla_Auxiliares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grilla__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipName>Grilla</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grilla__c/fields/Docente__c.field-meta.xml
<CustomField>
    <fullName>Docente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Docente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Docente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Grilla</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grilla__c/fields/Materia__c.field-meta.xml
<CustomField>
    <fullName>Materia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Materia</label>
    <referenceTo>Materia__c</referenceTo>
    <relationshipName>Grilla_de_horarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GrillaHorario__c/GrillaHorario__c.object-meta.xml
<CustomObject>
    <label>Grilla Horario</label>
    <nameField>
        <displayFormat>GH# {00000000}</displayFormat>
        <label>Grilla detalle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grilla Horarios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GrillaHorario__c/fields/desde__c.field-meta.xml
<CustomField>
    <fullName>desde__c</fullName>
    <label>Desde</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/GrillaHorario__c/fields/dia__c.field-meta.xml
<CustomField>
    <fullName>dia__c</fullName>
    <label>Dia de la semana</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lunes</fullName>
            </value>
            <value>
                <fullName>Martes</fullName>
            </value>
            <value>
                <fullName>Miercoles</fullName>
            </value>
            <value>
                <fullName>Jueves</fullName>
            </value>
            <value>
                <fullName>Viernes</fullName>
            </value>
            <value>
                <fullName>Sabado</fullName>
            </value>
            <value>
                <fullName>Domingo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GrillaHorario__c/fields/Grilla__c.field-meta.xml
<CustomField>
    <fullName>Grilla__c</fullName>
    <label>Grilla</label>
    <referenceTo>Grilla__c</referenceTo>
    <relationshipLabel>Grilla Horarios</relationshipLabel>
    <relationshipName>GrillaHorarios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GrillaHorario__c/fields/hasta__c.field-meta.xml
<CustomField>
    <fullName>hasta__c</fullName>
    <label>Hasta</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Materia__c/Materia__c.object-meta.xml
<CustomObject>
    <label>Materia</label>
    <nameField>
        <label>Nombre de Materia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GrillaController.cls
public with sharing class GrillaController {
    
    
    @AuraEnabled(cacheable=true)
    public static List<Grilla__c> getHorariosDivision( Id divisionId){
        try {            
            return [SELECT Materia__c, Materia__r.Name,
            (SELECT dia__c, desde__c, hasta__c
            FROM GrillaHorarios__r )  
            FROM Grilla__c 
            WHERE Division__c = :divisionId];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Grilla__c> getHorariosDocente( Id docenteId){
        try {            
            return [SELECT  Materia__c, Materia__r.Name,
            (SELECT dia__c, desde__c, hasta__c
            FROM GrillaHorarios__r )  
            FROM Grilla__c 
            WHERE Docente__c = :docenteId OR Auxiliar__c = :docenteId];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

    }

}