force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/anoEscolar__c.field-meta.xml
<CustomField>
    <fullName>anoEscolar__c</fullName>
    <label>Año escolar</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/nombre__c.field-meta.xml
<CustomField>
    <fullName>nombre__c</fullName>
    <formula>Text(anoEscolar__c) + &apos; &apos; + subdivision__c  +  &apos; &apos; + Text(Year(cicloLectivo__r.inicio__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>nombre</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/subdivision__c.field-meta.xml
<CustomField>
    <fullName>subdivision__c</fullName>
    <label>subdivision</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/test/TestDivisionTrigger.cls
@isTest
public class TestDivisionTrigger {
    @IsTest
    static void testRecordNames(){
        
        Test.startTest();
        // Valida el insert 
        TestDataFactory.getDivisiones();
        Division__c division = [Select Name, nombre__c From Division__c Limit 1];
        System.assertEquals(division.Name, division.nombre__c);
        // Valida el update
        division.anoEscolar__c = 2;
        division.subdivision__c = 'C';
        update division;
        Division__c divisionActualizada = [Select Name, nombre__c From Division__c Limit 1];
        System.assertEquals(divisionActualizada.Name, divisionActualizada.nombre__c);


        Test.stopTest();
        
    }

}