force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grilla__c/Grilla__c.object-meta.xml
<CustomObject>
    <label>Grilla de Materias</label>
    <nameField>
        <displayFormat>GR-{0000}-{YY}</displayFormat>
        <label>Nombre de Grilla</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grilla de Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grilla__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipName>Grilla</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestGrillaController.cls
@IsTest
public with sharing class TestGrillaController {
    @IsTest
    static void testGetHorarioDivision(){
        
        Test.startTest();
        Division__c division = TestDivisionTrigger.getDivisiones().get('1A');
        TestGrillaTrigger.getGrilla();
        
        List<Grilla__c> grilla =  GrillaController.getHorariosDivision(division.Id);
        System.assertEquals(grilla.size(),1);
        Test.stopTest();
        
    }

    @IsTest
    static void testGetHorarioDocente(){
        
        Test.startTest();
        TestGrillaTrigger.getGrilla();
        Contact docente = TestContactTrigger.getDocentes().get('Pedro');

        List<Grilla__c> grilla =  GrillaController.getHorariosDocente(docente.Id);
        System.assertEquals(grilla.size(),1);
        Test.stopTest();
        
    }

}