force-app/main/default/objects/Asistencia__c/Asistencia__c.object-meta.xml
<CustomObject>
    <description>Contiene las asistencias semanales de un alumno</description>
    <label>Asistencia</label>
    <nameField>
        <displayFormat>AS-{DDMMYY}-{0000}</displayFormat>
        <label>Nombre de Asistencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asistencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asistencia__c/fields/ano__c.field-meta.xml
<CustomField>
    <fullName>ano__c</fullName>
    <defaultValue>YEAR(Today())</defaultValue>
    <label>Ano</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Asistencia__c.field-meta.xml
<CustomField>
    <fullName>Asistencia__c</fullName>
    <formula>IF( ISPICKVAL(Lunes__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Lunes__c,  &apos;Tarde&apos;), 0.5,0))
+IF( ISPICKVAL(Martes__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Martes__c,  &apos;Tarde&apos;), 0.5,0))
+IF( ISPICKVAL(Miercoles__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Miercoles__c,  &apos;Tarde&apos;), 0.5,0))
+IF( ISPICKVAL(Jueves__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Jueves__c,  &apos;Tarde&apos;), 0.5,0))
+IF( ISPICKVAL(Viernes__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Viernes__c,  &apos;Tarde&apos;), 0.5,0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asistencia</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Desde__c.field-meta.xml
<CustomField>
    <fullName>Desde__c</fullName>
    <label>Desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Semana__c.field-meta.xml
<CustomField>
    <fullName>Semana__c</fullName>
    <description>Numero de semana del año</description>
    <inlineHelpText>Numero de semana del año, acepta valores entre 1 y 54</inlineHelpText>
    <label>Semana</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/SemanaText__c.field-meta.xml
<CustomField>
    <fullName>SemanaText__c</fullName>
    <description>Este campo es el mismo campo Semana pero en Texto porque el group by no permite que se haga con Numeros</description>
    <label>Semana para Agrupar</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AsistenciaTriggerHelper.cls
public with sharing class AsistenciaTriggerHelper {

    static public void setCalculatedValues( List<Asistencia__c> asistencias) {
        for( Asistencia__c asistencia :asistencias) {
            if ( asistencia.UniqueKey__c == null  ) {
                asistencia.UniqueKey__c = AsistenciasHelper.getUniqueKey(asistencia);
            }
            if ( asistencia.Desde__c == null && asistencia.ano__c > 0 && asistencia.Semana__c > 0 ) {
                asistencia.Desde__c = WeekHelper.getFirsDateOfWeek((Integer) asistencia.Semana__c, (Integer) asistencia.ano__c);
            }
            asistencia.SemanaText__c = String.valueOf(asistencia.Semana__c);
        }
    }
    
    static public void validateFields( List<Asistencia__c> asistencias) {
        for( Asistencia__c asistencia :asistencias) {
            if ( asistencia.Semana__c > 54 ||  asistencia.Semana__c < 1 ) {                
                asistencia.addError('El campo semana debe ser entre 1 y 54. Por ejemplo esta semana es la ' + WeekHelper.getWeekOfDate(Date.today()));
            }
            if ( asistencia.Ano__c > Date.Today().year() ) {
                asistencia.addError('El año no puede ser futuro cuando se cargan asistencias');
            }
        }
    
    }
}