force-app/main/default/objects/Asistencia__c/Asistencia__c.object-meta.xml
<CustomObject>
    <description>Contiene las asistencias semanales de un alumno</description>
    <label>Asistencia</label>
    <nameField>
        <displayFormat>AS-{DDMMYY}-{0000}</displayFormat>
        <label>Nombre de Asistencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asistencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asistencia__c/fields/ano__c.field-meta.xml
<CustomField>
    <fullName>ano__c</fullName>
    <defaultValue>YEAR(Today())</defaultValue>
    <label>Ano</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Asistencia__c.field-meta.xml
<CustomField>
    <fullName>Asistencia__c</fullName>
    <formula>IF( ISPICKVAL(Lunes__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Lunes__c,  &apos;Tarde&apos;), 0.5,0))
+IF( ISPICKVAL(Martes__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Martes__c,  &apos;Tarde&apos;), 0.5,0))
+IF( ISPICKVAL(Miercoles__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Miercoles__c,  &apos;Tarde&apos;), 0.5,0))
+IF( ISPICKVAL(Jueves__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Jueves__c,  &apos;Tarde&apos;), 0.5,0))
+IF( ISPICKVAL(Viernes__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Viernes__c,  &apos;Tarde&apos;), 0.5,0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asistencia</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Boletin__c.field-meta.xml
<CustomField>
    <fullName>Boletin__c</fullName>
    <label>Boletin</label>
    <referenceTo>Boletin__c</referenceTo>
    <relationshipLabel>Asistencias</relationshipLabel>
    <relationshipName>Asistencias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Jueves__c.field-meta.xml
<CustomField>
    <fullName>Jueves__c</fullName>
    <label>Jueves</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asistencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Lunes__c.field-meta.xml
<CustomField>
    <fullName>Lunes__c</fullName>
    <label>Lunes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asistencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Martes__c.field-meta.xml
<CustomField>
    <fullName>Martes__c</fullName>
    <label>Martes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asistencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Miercoles__c.field-meta.xml
<CustomField>
    <fullName>Miercoles__c</fullName>
    <label>Miercoles</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asistencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Semana__c.field-meta.xml
<CustomField>
    <fullName>Semana__c</fullName>
    <description>Numero de semana del año</description>
    <inlineHelpText>Numero de semana del año, acepta valores entre 1 y 54</inlineHelpText>
    <label>Semana</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/SemanaText__c.field-meta.xml
<CustomField>
    <fullName>SemanaText__c</fullName>
    <description>Este campo es el mismo campo Semana pero en Texto porque el group by no permite que se haga con Numeros</description>
    <label>Semana para Agrupar</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Viernes__c.field-meta.xml
<CustomField>
    <fullName>Viernes__c</fullName>
    <label>Viernes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asistencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Boletin__c/Boletin__c.object-meta.xml
<CustomObject>
    <label>Boletin</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boletines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boletin__c/fields/Asistencia__c.field-meta.xml
<CustomField>
    <fullName>Asistencia__c</fullName>
    <label>Asistencia</label>
    <summarizedField>Asistencia__c.Asistencia__c</summarizedField>
    <summaryForeignKey>Asistencia__c.Boletin__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Boletines</relationshipLabel>
    <relationshipName>Boletines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/nombreAlumno__c.field-meta.xml
<CustomField>
    <fullName>nombreAlumno__c</fullName>
    <formula>Alumno__r.FirstName + &apos; &apos; + Alumno__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre Completo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cicloLectivo__c/cicloLectivo__c.object-meta.xml
<CustomObject>
    <label>Ciclo Lectivo</label>
    <nameField>
        <label>Nombre de Ciclo Lectivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos Lectivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/cicloLectivo__c.field-meta.xml
<CustomField>
    <fullName>cicloLectivo__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ciclo Lectivo</label>
    <referenceTo>cicloLectivo__c</referenceTo>
    <relationshipLabel>Divisiones</relationshipLabel>
    <relationshipName>Divisiones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AsistenciasHelper.cls
public with sharing class AsistenciasHelper {
    static List<String> camposDias = new List<String>{ 'Lunes__c', 'Martes__c', 'Miercoles__c', 'Jueves__c', 'Viernes__c'};

    public static String getUniqueKey(Asistencia__c asistencia) {
        return asistencia.Boletin__c + '-' + String.valueOf(asistencia.Semana__c);
    }

    public class AsistenciasCiclo {
        Id cicloId;
        @AuraEnabled public List<AggregateResult> asistencias;

        public AsistenciasCiclo( Id cicloId){
            this.cicloId = cicloId;
            retrieve();
        }
        void retrieve() {
            asistencias = [SELECT  Boletin__r.Division__c, Boletin__r.Division__r.Name,  SemanaText__c, Sum(Asistencia__c) Faltas
                FROM Asistencia__c 
                WHERE Boletin__r.Division__r.CicloLectivo__c = :this.cicloId
                GROUP BY Boletin__r.Division__c, Boletin__r.Division__r.Name, SemanaText__c];
        }
    }

    public class AsistenciasBoletin {
        Id boletinId;
        @AuraEnabled public List<Asistencia__c> asistencias;

        public AsistenciasBoletin( Id boletinId){
            this.boletinId = boletinId;
            retrieve();
        }

        public void save(List<Map<String, Object>> draftValues) {
            try {
                List<Asistencia__c> asistencias = new List<Asistencia__c>();

                for ( Map<String, Object> draft :draftValues ){
                    Asistencia__c asistencia = new Asistencia__c( Boletin__c = this.boletinId, Semana__c =  Decimal.valueOf((String)draft.get('Semana__c')) );
                    asistencia.UniqueKey__c = getUniqueKey(asistencia);
                    for ( String campoDia : AsistenciasHelper.camposDias ){
                        if ( draft.containsKey(campoDia) ) {
                            asistencia.put( campoDia, draft.get(campoDia));
                        }
                    }
                    asistencias.add(asistencia);
                }    
                System.debug(asistencias);
                upsert asistencias UniqueKey__c;
            } catch ( Exception e ){
                System.debug(e.getMessage());
            }
        }


        void retrieve() {
            asistencias = [SELECT Id, Semana__c, Lunes__c, Martes__c, Miercoles__c, Jueves__c, Viernes__c, Asistencia__c 
                    FROM Asistencia__c 
                    WHERE Boletin__c = :this.boletinId ORDER BY Ano__c DESC, Semana__c DESC];
        }
    }

    public class AsistenciasDivision {
        public Id divisionId;
        @AuraEnabled public Integer semana;
        public Integer ano;
        @AuraEnabled public List<Boletin__c> boletines;
        @AuraEnabled public Map<Id, Asistencia__c> asistencias;
        
        public AsistenciasDivision( Id divisionId, Integer semana ){
            this.divisionId = divisionId;
            if ( semana == 0) {
                semana = WeekHelper.getWeekOfDate(Date.today());
                ano = Date.today().year();
            }
            this.semana = semana;

            retrieve();            
        }
        
        public void save(List<Map<String, Object>> draftValues) {
            try {
                List<Asistencia__c> asistencias = new List<Asistencia__c>();

                for ( Map<String, Object> draft :draftValues ){
                    Asistencia__c asistencia = new Asistencia__c( Boletin__c = (String)draft.get('id'), Semana__c = this.semana);
                    asistencia.UniqueKey__c = getUniqueKey(asistencia);
                    for ( String campoDia : AsistenciasHelper.camposDias ){
                        if ( draft.containsKey(campoDia) ) {
                            asistencia.put( campoDia, draft.get(campoDia));
                        }
                    }
                    asistencias.add(asistencia);
                }    
                System.debug(asistencias);
                upsert asistencias UniqueKey__c;
            } catch ( Exception e ){
                System.debug(e.getMessage());
            }
        }

        void retrieve() {
            List<Boletin__c> boletines = [SELECT nombreAlumno__c, 
                (SELECT Id, Lunes__c, Martes__c, Miercoles__c, Jueves__c, Viernes__c , Asistencia__c
                FROM Asistencias__r 
                WHERE Semana__c = :this.semana )  
                FROM Boletin__c 
                WHERE Division__c = :this.divisionId];            
            
            this.boletines = new List<Boletin__c>();
            this.asistencias = new Map<Id, Asistencia__c>();

            for( Boletin__c boletin: boletines){
                this.boletines.add(boletin);
                if ( boletin.Asistencias__r.size() > 0 ) {
                    this.asistencias.put(boletin.Id, boletin.Asistencias__r.get(0));
                }
            }
        }
    }

}