force-app/main/default/objects/Asistencia__c/Asistencia__c.object-meta.xml
<CustomObject>
    <description>Contiene las asistencias semanales de un alumno</description>
    <label>Asistencia</label>
    <nameField>
        <displayFormat>AS-{DDMMYY}-{0000}</displayFormat>
        <label>Nombre de Asistencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asistencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asistencia__c/fields/Asistencia__c.field-meta.xml
<CustomField>
    <fullName>Asistencia__c</fullName>
    <formula>IF( ISPICKVAL(Lunes__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Lunes__c,  &apos;Tarde&apos;), 0.5,0))
+IF( ISPICKVAL(Martes__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Martes__c,  &apos;Tarde&apos;), 0.5,0))
+IF( ISPICKVAL(Miercoles__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Miercoles__c,  &apos;Tarde&apos;), 0.5,0))
+IF( ISPICKVAL(Jueves__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Jueves__c,  &apos;Tarde&apos;), 0.5,0))
+IF( ISPICKVAL(Viernes__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Viernes__c,  &apos;Tarde&apos;), 0.5,0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asistencia</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Boletin__c.field-meta.xml
<CustomField>
    <fullName>Boletin__c</fullName>
    <label>Boletin</label>
    <referenceTo>Boletin__c</referenceTo>
    <relationshipLabel>Asistencias</relationshipLabel>
    <relationshipName>Asistencias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Boletin__c/Boletin__c.object-meta.xml
<CustomObject>
    <label>Boletin</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boletines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boletin__c/fields/Asistencia__c.field-meta.xml
<CustomField>
    <fullName>Asistencia__c</fullName>
    <label>Asistencia</label>
    <summarizedField>Asistencia__c.Asistencia__c</summarizedField>
    <summaryForeignKey>Asistencia__c.Boletin__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Boletines</relationshipLabel>
    <relationshipName>Boletines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cicloLectivo__c/cicloLectivo__c.object-meta.xml
<CustomObject>
    <label>Ciclo Lectivo</label>
    <nameField>
        <label>Nombre de Ciclo Lectivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos Lectivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cicloLectivo__c/fields/fin__c.field-meta.xml
<CustomField>
    <fullName>fin__c</fullName>
    <label>Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cicloLectivo__c/fields/inicio__c.field-meta.xml
<CustomField>
    <fullName>inicio__c</fullName>
    <label>Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cicloLectivo__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programa</label>
    <referenceTo>Programa__c</referenceTo>
    <relationshipLabel>Ciclo Lectivos</relationshipLabel>
    <relationshipName>cicloLectivo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/anoEscolar__c.field-meta.xml
<CustomField>
    <fullName>anoEscolar__c</fullName>
    <label>Año escolar</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/cicloLectivo__c.field-meta.xml
<CustomField>
    <fullName>cicloLectivo__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ciclo Lectivo</label>
    <referenceTo>cicloLectivo__c</referenceTo>
    <relationshipLabel>Divisiones</relationshipLabel>
    <relationshipName>Divisiones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <formula>cicloLectivo__r.Programa__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Programa</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/Evaluacion__c.object-meta.xml
<CustomObject>
    <label>Evaluacion</label>
    <nameField>
        <displayFormat>EV# {00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Evaluacion__c/fields/Boletin__c.field-meta.xml
<CustomField>
    <fullName>Boletin__c</fullName>
    <label>Boletin</label>
    <referenceTo>Boletin__c</referenceTo>
    <relationshipLabel>Evaluaciones</relationshipLabel>
    <relationshipName>Evaluaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Grilla__c.field-meta.xml
<CustomField>
    <fullName>Grilla__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grilla de Materias</label>
    <referenceTo>Grilla__c</referenceTo>
    <relationshipLabel>Evaluaciones</relationshipLabel>
    <relationshipName>Evaluaciones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Materia__c.field-meta.xml
<CustomField>
    <fullName>Materia__c</fullName>
    <formula>Grilla__r.Materia__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Materia</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Nota1__c.field-meta.xml
<CustomField>
    <fullName>Nota1__c</fullName>
    <label>Nota1</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Nota2__c.field-meta.xml
<CustomField>
    <fullName>Nota2__c</fullName>
    <label>Nota2</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Evaluacion__c/fields/Nota3__c.field-meta.xml
<CustomField>
    <fullName>Nota3__c</fullName>
    <label>Nota3</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grilla__c/Grilla__c.object-meta.xml
<CustomObject>
    <label>Grilla de Materias</label>
    <nameField>
        <displayFormat>GR-{0000}-{YY}</displayFormat>
        <label>Nombre de Grilla</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grilla de Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grilla__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipName>Grilla</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grilla__c/fields/Materia__c.field-meta.xml
<CustomField>
    <fullName>Materia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Materia</label>
    <referenceTo>Materia__c</referenceTo>
    <relationshipName>Grilla_de_horarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GrillaHorario__c/GrillaHorario__c.object-meta.xml
<CustomObject>
    <label>Grilla Horario</label>
    <nameField>
        <displayFormat>GH# {00000000}</displayFormat>
        <label>Grilla detalle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grilla Horarios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GrillaHorario__c/fields/Grilla__c.field-meta.xml
<CustomField>
    <fullName>Grilla__c</fullName>
    <label>Grilla</label>
    <referenceTo>Grilla__c</referenceTo>
    <relationshipLabel>Grilla Horarios</relationshipLabel>
    <relationshipName>GrillaHorarios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Materia__c/Materia__c.object-meta.xml
<CustomObject>
    <label>Materia</label>
    <nameField>
        <label>Nombre de Materia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Materia__c/fields/anoEscolar__c.field-meta.xml
<CustomField>
    <fullName>anoEscolar__c</fullName>
    <description>El Año escolar representa el año dentro del programa. Se asume que un programa tiene como maximo 9 años</description>
    <inlineHelpText>Año dentro del programa, por ejemplo 1 seria primer año.</inlineHelpText>
    <label>Año escolar</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Materia__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programa</label>
    <referenceTo>Programa__c</referenceTo>
    <relationshipLabel>Materias</relationshipLabel>
    <relationshipName>Materias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramaEvaluacion__c/ProgramaEvaluacion__c.object-meta.xml
<CustomObject>
    <description>Cada programa define los tipos de evalucaciones que quedaran reflejados como columnas del boletin. 
Cada materia pondra sus notas, ya sean conceptuales o numericas de acuerdo a esta definicion</description>
    <label>Evaluacion de un Programa</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluaciones de los programas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramaEvaluacion__c/fields/Campo__c.field-meta.xml
<CustomField>
    <fullName>Campo__c</fullName>
    <label>Campo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nota1__c</fullName>
                <label>Nota1</label>
            </value>
            <value>
                <fullName>Nota2__c</fullName>
                <label>Nota2</label>
            </value>
            <value>
                <fullName>Nota3__c</fullName>
                <label>Nota3</label>
            </value>
            <value>
                <fullName>Nota4__c</fullName>
                <label>Nota4</label>
            </value>
            <value>
                <fullName>Nota5__c</fullName>
                <label>Nota5</label>
            </value>
            <value>
                <fullName>Conceptual1__c</fullName>
                <label>Conceptual1</label>
            </value>
            <value>
                <fullName>Conceptual2__c</fullName>
                <label>Conceptual2</label>
            </value>
            <value>
                <fullName>Conceptual3__c</fullName>
                <label>Conceptual3</label>
            </value>
            <value>
                <fullName>Conceptual4__c</fullName>
                <label>Conceptual4</label>
            </value>
            <value>
                <fullName>Conceptual5__c</fullName>
                <label>Conceptual5</label>
            </value>
            <value>
                <fullName>Opcion1</fullName>
            </value>
            <value>
                <fullName>Opcion2</fullName>
            </value>
            <value>
                <fullName>Opcion3</fullName>
            </value>
            <value>
                <fullName>Opcion4</fullName>
            </value>
            <value>
                <fullName>Opcion5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramaEvaluacion__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <label>Programa</label>
    <referenceTo>Programa__c</referenceTo>
    <relationshipLabel>Evaluaciones de los programas</relationshipLabel>
    <relationshipName>ProgramaEvaluaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProgramaEvaluacion__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Las notas son valoraciones numericas del 1 al 10, mientras que las conceptuales son listas de valoraciones por ejemplo Insuficiente, Regular. Bien, Muy Bien y Excelente.</description>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nota</fullName>
            </value>
            <value>
                <fullName>Conceptual</fullName>
            </value>
            <value>
                <fullName>Formula</fullName>
            </value>
            <value>
                <fullName>Opcion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/test/TestDataFactory.cls
// TODO: Que puedan las relaciones estar tambien en memoria

public class TestDataFactory {    
    static final Boolean DEFAULT_INSERT = true;
    static final Integer DEFAULT_RECORDS = 3;

    static private Map<String,Division__c> divisiones;
    static private Map<String,Contact> alumnos;
    static private Map<String,Contact> docentes;
    static private Map<String, Asistencia__c> asistencias;
    static private Map<String, Boletin__c> boletines;
    static private Map<String, Grilla__c> grilla;
    static private Map<String, CicloLectivo__c> ciclos; 
    static private Map<String, Evaluacion__c> evaluaciones;
    static private Map<String, ProgramaEvaluacion__c> programaEvaluaciones;
    static private Map<String,Programa__c> programas;
    static private Map<String, Materia__c> materias;

    
    private static void resolverId(List<SObject> objects, String relation, String field ) {
        for ( SObject o: objects){
            o.put(field, o.getSObject(relation).get('Id'));
        }
    }
    private static String getName(String prefix, Integer index, Map<String, SObject> mp) {
        return getName(prefix, index, mp.size() );
    }
    private static String getName(String prefix, Integer index, Integer max) {
        return getName( prefix, Math.mod(index, max));
    }
    private static String getName(String prefix, Integer index) {
        if ( !prefix.contains('{0}')) prefix = prefix + '-{0}'; 
        return String.format(prefix, new List<Object> { index} );        
    }
    
    public static void makeMaterias(Boolean insertValues, Integer qty) {
        materias = new Map<String, Materia__c>();

        for( Integer index = 0; index < qty; index++ ) {
            String name = getName('M', index);
            materias.put( name, new Materia__c( Name = name, anoEscolar__c = Math.Mod(index, 5) ) );
        }
        if ( insertValues ) {
            insert materias.values();
        }
    }

    public static Map<String, Materia__c> getMaterias(){
        if ( materias == null ) {
            makeMaterias(DEFAULT_INSERT, DEFAULT_RECORDS);
        }
        return materias;
    }

    public static void makeProgramas(Boolean insertValues, Integer qty) {
        programas = new Map<String, Programa__c>();
        
        for( Integer index = 0; index < qty; index++ ) {
            String name = getName('P', index);
            programas.put( name, new Programa__c( Name = name ) );
        }
        if ( insertValues ) {
            insert programas.values();
        }
    }

    static public Map<String, Programa__c> getProgramas(){
        if ( programas == null ) {
            makeProgramas(DEFAULT_INSERT, DEFAULT_RECORDS);
        }
        return programas;
    }

    public static Map<String, ProgramaEvaluacion__c> getProgramaEvaluaciones(){
        if ( programaEvaluaciones == null ) {
            makeProgramaEvaluaciones(DEFAULT_INSERT, DEFAULT_RECORDS);
        }
        return programaEvaluaciones;
    }

    public static void makeProgramaEvaluaciones( Boolean insertValues, Integer qty){
        programaEvaluaciones = new Map<String, ProgramaEvaluacion__c>(); 

        Integer index = 1, i = 1;
        while ( qty > 0 ){
            Programa__c programa = getProgramas().get( getName('P', index++) );
            
            programaEvaluaciones.put( getName('P', index++), new ProgramaEvaluacion__c( Programa__c = programa.Id,  Tipo__c = 'Nota', Campo__c = 'Nota1__c'));
            programaEvaluaciones.put( getName('P', index++), new ProgramaEvaluacion__c( Programa__c = programa.Id,  Tipo__c = 'Nota', Campo__c = 'Nota2__c'));
            programaEvaluaciones.put( getName('P', index++), new ProgramaEvaluacion__c( Programa__c = programa.Id,  Tipo__c = 'Nota', Campo__c = 'Nota3__c'));
            qty = qty -3;
        }
         
        if( insertValues ) {
            insert programaEvaluaciones.values();
        } 
    }    

    public static Map<String, Evaluacion__c> getEvaluaciones(){
        if ( evaluaciones == null ) {
            makeEvaluaciones(DEFAULT_INSERT, DEFAULT_RECORDS);
        }
        return evaluaciones;
    }

    public static void makeEvaluaciones( Boolean insertValues, Integer qty){
        evaluaciones = new Map<String, Evaluacion__c>();
       
        for( Integer index = 0; index < qty; index++ ) {
            
            Boletin__c boletin = getBoletines().get(getName('B', index, boletines));
            Grilla__c grilla = getGrilla().get(getName('G', index, grilla));
    
            evaluaciones.put( 'B-' + index + ' G-' + index, new Evaluacion__c( Boletin__c =boletin.Id, Grilla__c = grilla.id, Nota1__c = 10) );
        }
        
        if( insertValues ) {
            insert evaluaciones.values();
            system.debug(evaluaciones.values().size());
        } 
    }

    static public Map<String, CicloLectivo__c> getCiclos(){
        if ( ciclos == null) {
            makeCiclos(DEFAULT_INSERT, DEFAULT_RECORDS);
        }
        return ciclos;
    }

    public static void makeCiclos( Boolean insertValues, Integer qty){
        ciclos = new Map<String, CicloLectivo__c>();
        Integer index = 1;
        while ( qty > 0 ){
            Programa__c programa = getProgramas().get('P-' + index);
            ciclos.put( getName('CP', index), new CicloLectivo__c( Name = 'CP-' + index, Programa__c = programa.Id, Inicio__c = Date.Today().addDays(-540), Fin__c = Date.Today().addDays(-181) ) );
            ciclos.put( getName('CA', index), new CicloLectivo__c( Name = 'CA-' + index, Programa__c = programa.Id, Inicio__c = Date.Today().addDays(-180), Fin__c = Date.Today().addDays(180) ) );
            ciclos.put( getName('CF', index), new CicloLectivo__c( Name = 'CF+' + index, Programa__c = programa.Id, Inicio__c = Date.Today().addDays(181), Fin__c = Date.Today().addDays(540) ) );
            qty = qty -3;
            index++;
        }
        if( insertValues ) {
            insert ciclos.values();
        }
    }

    public static Map<String, Grilla__c> getGrilla(){
        if ( grilla == null ) {
            makeGrilla(DEFAULT_INSERT, DEFAULT_RECORDS);
        }
        return grilla;
    }

    public static void makeGrilla( Boolean insertValues, Integer qty){    
        grilla = new Map<String, Grilla__c>();
        List<GrillaHorario__c> horarios = new List<GrillaHorario__c>();
        
        for( Integer index = 0; index < qty; index++ ) { 
            Division__c division = getDivisiones().get( getName('D', index, divisiones) );
            Materia__c materia = getMaterias().get( getName('M', index, materias));
            Contact docente = getDocentes().get( getName('D', index, docentes));
            String name = getName('G', index);
            grilla.put( name, new Grilla__c( Materia__c = materia.Id, Docente__c = docente.Id, Division__c = division.Id ) );
            System.debug(grilla.get(name));
            horarios.add( new GrillaHorario__c( Grilla__r = grilla.get(name), dia__c = 'Lunes', desde__c = Time.newInstance(10, 0,0,0), hasta__c =Time.newInstance(11, 0,0,0)) ); 
        }

        if( insertValues ) {
            insert grilla.values();
            resolverId(horarios, 'Grilla__r', 'Grilla__c'); 
            insert horarios;
        }
    }

    public static Map<String, Boletin__c> getBoletines(){
        if ( boletines == null ) {
            makeBoletines(DEFAULT_INSERT, DEFAULT_RECORDS);
        }
        return boletines;
    }

    public static void makeBoletines( Boolean insertValues, Integer qty){    
        boletines = new Map<String, Boletin__c>();

        for( Integer index = 0; index < qty; index++ ) { 
            Division__c division = getDivisiones().get( getName('D', index, 2) );
            Contact alumno = getAlumnos().get(getName('A', index, alumnos) );

            boletines.put( getName('B', index), new Boletin__c( Division__c = division.Id, Alumno__c = alumno.Id) );
        }

        if( insertValues ) {
            insert boletines.values();
        }
    }

    public static Map<String, Asistencia__c> getAsistencias(){
        if ( asistencias == null ) {
            makeAsistencias(DEFAULT_INSERT, DEFAULT_RECORDS);
        }
        return asistencias;
    }
    
    public static void makeAsistencias( Boolean insertValues, Integer qty){
        asistencias = new Map<String, Asistencia__c>();

        Integer index = 1;
        while ( qty > 0 ){
            Boletin__c boletin = getBoletines().get( getName('B', index, boletines) );
            asistencias.put( getName('B-{0} S-1', index), new Asistencia__c( Boletin__c =boletin.Id, Semana__c = 1, Lunes__c = 'Asistio', Martes__c = 'Asistio', Miercoles__c = 'Asistio', Jueves__c = 'Asistio', Viernes__c = 'Asistio') );
            asistencias.put( getName('B-{0} S-2', index), new Asistencia__c( Boletin__c =boletin.Id, Semana__c = 2, Lunes__c = 'Tarde', Martes__c = 'Asistio', Miercoles__c = 'Asistio', Jueves__c = 'Asistio', Viernes__c = 'Asistio') );
            qty = qty-2;
        }

        if( insertValues ) {
            insert asistencias.values();
            system.debug(asistencias.values().size());
        } 
    }
    
    static public Map<String, Division__c> getDivisiones(){
        if ( divisiones == null ) {
            makeDivisiones(DEFAULT_INSERT, DEFAULT_RECORDS);
        }
        return divisiones;
    }

    public static void makeDivisiones( Boolean insertValues, Integer qty){
        divisiones = new Map<String, Division__c>();
        
        for( Integer index = 0; index < qty; index++ ) { 
            CicloLectivo__c ciclo = getCiclos().get('CA-1');    
            divisiones.put( getName('D', index ), new Division__c( CicloLectivo__c = ciclo.Id, anoEscolar__c = Math.Mod(index,5), subdivision__c = String.valueOf(index) ) );
        }

        if( insertValues ) {
            insert divisiones.values();
        }
    }


    static public Map<String,Contact> getAlumnos(){
        if  (alumnos == null ) {
            makeAlumnos(DEFAULT_INSERT, DEFAULT_RECORDS);
        }
        return alumnos;
    }

    public static void makeAlumnos( Boolean insertValues, Integer qty){
        alumnos = new Map<String,Contact>();
        
        for( Integer index = 0; index < qty; index++ ) { 
            alumnos.put( getName('A', index), new Contact( FirstName = 'First' + index ,LastName= 'Last' + index , recordTypeId = ContactHelper.getRecordTypeIdForAlumno(), Documento__c = '123' + index, TipoDeDocumento__c = 'DNI' ) );
        }

        if( insertValues ) {
            insert alumnos.values();
        }
    }

    static public Map<String,Contact> getDocentes(){
        if  (docentes == null ) {
            makeDocentes(DEFAULT_INSERT, DEFAULT_RECORDS);
        }
        return docentes;
    }

    public static void makeDocentes( Boolean insertValues, Integer qty){
        docentes = new Map<String,Contact>();
        for( Integer index = 0; index < qty; index++ ) { 
            docentes.put( getName('D', index), new Contact( FirstName = 'First' + index ,LastName= 'Last' + index , recordTypeId = ContactHelper.getRecordTypeIdForDocente(), Documento__c = '321' + index, TipoDeDocumento__c = 'DNI' ) );
        }

        if( insertValues ) {
            insert docentes.values();
        }
    }

}