force-app/main/default/objects/Asistencia__c/Asistencia__c.object-meta.xml
<CustomObject>
    <description>Contiene las asistencias semanales de un alumno</description>
    <label>Asistencia</label>
    <nameField>
        <displayFormat>AS-{DDMMYY}-{0000}</displayFormat>
        <label>Nombre de Asistencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asistencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asistencia__c/fields/Asistencia__c.field-meta.xml
<CustomField>
    <fullName>Asistencia__c</fullName>
    <formula>IF( ISPICKVAL(Lunes__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Lunes__c,  &apos;Tarde&apos;), 0.5,0))
+IF( ISPICKVAL(Martes__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Martes__c,  &apos;Tarde&apos;), 0.5,0))
+IF( ISPICKVAL(Miercoles__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Miercoles__c,  &apos;Tarde&apos;), 0.5,0))
+IF( ISPICKVAL(Jueves__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Jueves__c,  &apos;Tarde&apos;), 0.5,0))
+IF( ISPICKVAL(Viernes__c,&apos;Falto&apos;), 1, IF(ISPICKVAL( Viernes__c,  &apos;Tarde&apos;), 0.5,0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asistencia</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Boletin__c.field-meta.xml
<CustomField>
    <fullName>Boletin__c</fullName>
    <label>Boletin</label>
    <referenceTo>Boletin__c</referenceTo>
    <relationshipLabel>Asistencias</relationshipLabel>
    <relationshipName>Asistencias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Jueves__c.field-meta.xml
<CustomField>
    <fullName>Jueves__c</fullName>
    <label>Jueves</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asistencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Lunes__c.field-meta.xml
<CustomField>
    <fullName>Lunes__c</fullName>
    <label>Lunes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asistencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Martes__c.field-meta.xml
<CustomField>
    <fullName>Martes__c</fullName>
    <label>Martes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asistencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Miercoles__c.field-meta.xml
<CustomField>
    <fullName>Miercoles__c</fullName>
    <label>Miercoles</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asistencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Semana__c.field-meta.xml
<CustomField>
    <fullName>Semana__c</fullName>
    <description>Numero de semana del año</description>
    <inlineHelpText>Numero de semana del año, acepta valores entre 1 y 54</inlineHelpText>
    <label>Semana</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Viernes__c.field-meta.xml
<CustomField>
    <fullName>Viernes__c</fullName>
    <label>Viernes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asistencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Boletin__c/Boletin__c.object-meta.xml
<CustomObject>
    <label>Boletin</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boletines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boletin__c/fields/Asistencia__c.field-meta.xml
<CustomField>
    <fullName>Asistencia__c</fullName>
    <label>Asistencia</label>
    <summarizedField>Asistencia__c.Asistencia__c</summarizedField>
    <summaryForeignKey>Asistencia__c.Boletin__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/test/TestAsistenciasTrigger.cls
@IsTest
public class TestAsistenciasTrigger {
    static private Map<String, Asistencia__c> asistencias;

        public static Map<String, Asistencia__c> getAsistencias(){
            return getAsistencias(true);
        }

        public static Map<String, Asistencia__c> getAsistencias( Boolean insertValues){
        if ( asistencias == null ) {
            Boletin__c boletin = TestBoletinTrigger.getBoletines().get('Juan 1A');
            asistencias = new Map<String, Asistencia__c>();            
            asistencias.put( 'Juan 1A S1', new Asistencia__c( Boletin__c =boletin.Id, Semana__c = 1, Lunes__c = 'Asistio', Martes__c = 'Asistio', Miercoles__c = 'Asistio', Jueves__c = 'Asistio', Viernes__c = 'Asistio') );
            asistencias.put( 'Juan 1A S2', new Asistencia__c( Boletin__c =boletin.Id, Semana__c = 2, Lunes__c = 'Tarde', Martes__c = 'Asistio', Miercoles__c = 'Asistio', Jueves__c = 'Asistio', Viernes__c = 'Asistio') );
            if( insertValues ) {
                insert asistencias.values();
                system.debug(asistencias.values().size());
            } 
        }
        return asistencias;
    }
}