force-app/main/default/objects/Evaluacion__c/Evaluacion__c.object-meta.xml
<CustomObject>
    <label>Evaluacion</label>
    <nameField>
        <displayFormat>EV# {00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Evaluacion__c/fields/Grilla__c.field-meta.xml
<CustomField>
    <fullName>Grilla__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grilla de Materias</label>
    <referenceTo>Grilla__c</referenceTo>
    <relationshipLabel>Evaluaciones</relationshipLabel>
    <relationshipName>Evaluaciones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grilla__c/Grilla__c.object-meta.xml
<CustomObject>
    <label>Grilla de Materias</label>
    <nameField>
        <displayFormat>GR-{0000}-{YY}</displayFormat>
        <label>Nombre de Grilla</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grilla de Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EvaluacionesController.cls
public with sharing class EvaluacionesController {

    @AuraEnabled(cacheable=true)
    public static EvaluacionesHelper.EvaluacionesGrilla getByGrilla( Id grillaId){
        return new EvaluacionesHelper.EvaluacionesGrilla(grillaId);
    }

    @AuraEnabled(cacheable=true)
    public static EvaluacionesHelper.EvaluacionesDivision getByDivision( Id divisionId,  Id grillaId){
        return  new EvaluacionesHelper.EvaluacionesDivision(divisionId, grillaId);        
    }   
    
    @AuraEnabled
    public static void saveByDivision( String divisionId, String grillaId, List<Map<String, Object>> draftValues){
        EvaluacionesHelper.EvaluacionesDivision helper = new EvaluacionesHelper.EvaluacionesDivision(divisionId, grillaId);
        helper.save(draftValues);
    }
    
    @AuraEnabled(cacheable=true)
    public static EvaluacionesHelper.EvaluacionesBoletin getByBoletin( Id boletinId){
        return  new EvaluacionesHelper.EvaluacionesBoletin(boletinId);
    }

    @AuraEnabled
    public static void saveByBoletin( String boletinId, List<Map<String, Object>> draftValues){
        EvaluacionesHelper.EvaluacionesBoletin helper = new EvaluacionesHelper.EvaluacionesBoletin(boletinId);
        helper.save(draftValues);
    }

    @AuraEnabled(cacheable=true)
    public static List<Grilla__c>  getGrilla( Id divisionId){
        return DivisionHelper.getGrilla(divisionId);
    }

    @AuraEnabled(cacheable=true)
    public static EvaluacionesHelper.Programa  getPrograma( Id divisionId){
        return EvaluacionesHelper.getPrograma(divisionId);
    }


    @AuraEnabled(cacheable=false)
    public static void saveEvaluaciones( List<Evaluacion__c> evaluaciones){
    }

}